### ISSUE TITLE
Links to content in this submodule are broken

### ISSUE THREAD

**Issue by davis278** [CDAT/Jupyter-notebooks#2]
@doutriaux1 content in the Jupyter-notebooks submodule which should show up on the CDAT Tutorials page (https://cdat.llnl.gov/tutorials.html) is not displaying on the html page.  
@mauzey1 checked the logs and the CDAT site is getting updated each hour with the content from cdat.github.io. 
I've checked some of the links to the html pages and the images that are not showing up on the Tutorials.html page - the paths I checked appear to be correct.

Perhaps one of the following two pages can provide a solution...
https://stackoverflow.com/questions/31117120/submodule-not-showing-up-in-repo or
https://stackoverflow.com/questions/3336995/git-will-not-init-sync-update-new-submodules

**Comment by doutriaux1** [comment]
yes we need to update the cronjob

**Comment by mauzey1** [comment]
@davis278 @doutriaux1 
I ran the command `git submodule update --init --recursive` in the repo on the server to make it checkout the Jupyter-notebooks submodule.

I have made a pull requests in the cdat.github.io repo to make the deploy.bash script also update the submodules.
https://github.com/CDAT/cdat.github.io/pull/177

**Comment by davis278** [comment]
@doutriaux1 @mauzey1 
Some of the links on the page referenced the wrong subdirectory so I've updated those links and created a pull request, https://github.com/CDAT/cdat.github.io/pull/178. While testing using Jekyll, it appeared that my changes did not fix things, but perhaps I need to do some git magic on my local repo? I'll check again tomorrow once the cronjob has run.

**Comment by davis278** [comment]
Problem resolved; closing the issue.
